# Create the /opt/dinfo/etc/dbs.conf and
# /var/www/vhosts/businesscard.epfl.ch/private/etc/access_conf secrets
- name: "businesscard secrets"
  openshift:
    state: latest
    apiVersion: v1
    kind: Secret
    metadata:
      name: businesscard-secrets
      namespace: '{{ openshift_namespace }}'
    type: Opaque
    data:
      dbs.conf: '{{ _dbs_conf | base64 }}'
  vars:
    _dbs_conf: |
      {% for k, el in keybase_secrets.cadi_dbs.items() %}
      {{ k }}	{{ el.db_name }}	{{ el.db_host }}	{{ el.db_user }}	{{ el.db_pass }}
      {% endfor %}
  tags:
    - all
    - all_run
    - businesscard.dbs
    - businesscard.secrets



- name: Service
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          app: businesscard
        name: businesscard-service
        namespace: "{{ openshift_namespace }}"
      spec:
        ports:
          - name: 8080-tcp
            port: 8080
            protocol: TCP
            targetPort: 8080
        selector:
          deploymentconfig: businesscard
        sessionAffinity: None
        type: ClusterIP
  tags:
    - all
    - all_run
    - businesscard.service


