- include_vars: businesscard-vars.yml
  tags: always

- include_tasks:
    file: businesscard-openshift-build-tasks.yml
    apply:
      tags:
        - businesscard.openshift-build
  tags: always

- include_tasks:
    file: businesscard-openshift-run-tasks.yml
    apply:
      tags:
        - businesscard.openshift-run
  tags: always
