businesscard_build_openshift_namespace: businesscard-test
_dinfo_build_keybase_dir: "/keybase/team/epfl_si.build_common"
dinfo_build_cadi_libs_ssh_secret_key_path: "{{ _dinfo_build_keybase_dir }}/id_rsa_c4science_idevfsd-checkouter"
dinfo_build_cadi_libs_ssh_known_hosts_cmd: "ssh-keyscan c4science.ch"
