keybase_secrets: >-
  {{       _keybase_secrets_prod    if inventory_environment == "prod"
      else _keybase_secrets_preprod if inventory_environment == "test"
      else None }}
_keybase_secrets_prod: >-
    {{ lookup('file', '/keybase/team/epfl_bsnscrd/secrets-prod.yml') | from_yaml }}
_keybase_secrets_preprod: >-
    {{ lookup('file', '/keybase/team/epfl_bsnscrd/secrets-test.yml') | from_yaml }}

businesscard_hostname: >-
  {{ "businesscard.epfl.ch" if inventory_environment == "prod"
      else "businesscard-preprod.epfl.ch" if inventory_environment == "test"
      else "localhost" }}

businesscard_routes: >-
  {{ ["businesscard.epfl.ch"] if inventory_environment == "prod"
      else ["businesscard-preprod.epfl.ch", "businesscard-preprod.epfl.ch"] if inventory_environment == "test"
      else "localhost" }}

businesscard_base_image_pull_secret_name: github-package-common-libs-pull

businesscard_vhost_dir: businesscard.epfl.ch

businesscard_build_openshift_namespace: businesscard-test

apache_conf_log_level: >-
  {{ "error" if inventory_environment == "prod" else "debug" }}

tequila_hostname: >-
  {{ "tequila.epfl.ch" if inventory_environment == "prod"
      else "test-tequila.epfl.ch" if inventory_environment == "test"
      else "localhost" }}

# docker-registry.default.svc
# os-docker-registry.epfl.ch
_docker_openshift_repository: docker-registry.default.svc
_cadi_base_image_name: cadi-libs-idevfsd
_cadi_base_image_tag: latest
cadi_base_image_uri: >-
  docker-registry.default.svc:5000/dinfo-cicd/cadi-libs-idevfsd

businesscard_image_name: businesscard
businesscard_image_tag: >-
    {{ "prod" if inventory_environment == "prod" else "develop" }}

dinfo_build_openshift_namespace: dinfo-cicd
dinfo_build_keybase_dir: "/keybase/team/epfl_si.build_common"
_dinfo_keybase_build_secrets: >-
  {{ lookup("file", "{{ dinfo_build_keybase_dir }}/build-secrets.yml") |
     from_yaml }}
dinfo_build_c4science_credentials: >-
  {{ _dinfo_keybase_build_secrets.c4science_clone_credentials }}
dinfo_build_cadi_libs_ssh_secret_key_path: "{{ dinfo_build_keybase_dir }}/id_rsa_c4science_idevfsd-checkouter"
dinfo_build_cadi_libs_ssh_known_hosts_cmd: "ssh-keyscan c4science.ch"
businesscard_git_branch: "saphirevert/test"
