keybase_secrets: >-
  {{       _keybase_secrets_prod    if inventory_environment == "prod"
      else _keybase_secrets_preprod if inventory_environment == "test"
      else None }}
_keybase_secrets_prod: >-
    {{ lookup('file', '/keybase/team/epfl_bsnscrd/secrets-prod.yml') | from_yaml }}
_keybase_secrets_preprod: >-
    {{ lookup('file', '/keybase/team/epfl_bsnscrd/secrets-test.yml') | from_yaml }}

keybase_businesscard_service_mail_account: >-
    {{ lookup('file', '/keybase/team/epfl_bsnscrd/service.yml') | from_yaml }}

businesscard_hostname: >-
  {{ "businesscard.epfl.ch" if inventory_environment == "prod"
      else "businesscard-preprod.epfl.ch" if inventory_environment == "test"
      else "localhost" }}

businesscard_routes: >-
  {{ ["businesscard.epfl.ch", "businesscard.128.178.222.83.nip.io"] if inventory_environment == "prod"
      else ["businesscard-preprod.epfl.ch", "test-businesscard.128.178.222.83.nip.io", "businesscard-test.epfl.ch"] if inventory_environment == "test"
      else "localhost" }}

businesscard_base_image_pull_secret_name: github-package-common-libs-pull

businesscard_git_repository: ssh://git@c4science.ch/diffusion/9003/businesscard.git
# Note that the `master` branch contains a Dockerfile, but we don't
# want to use it (until this one is merged):
businesscard_git_branch: master

businesscard_vhost_dir: businesscard.epfl.ch

businesscard_build_openshift_namespace: >- 
  {{ "businesscard-prod" if inventory_environment == "prod"
      else "businesscard-test" if inventory_environment == "test" }}
tequila_hostname: >-
  {{ "tequila.epfl.ch" if inventory_environment == "prod"
      else "test-tequila.epfl.ch" if inventory_environment == "test"
      else "localhost" }}
tequila_environment: >-
  {{ "prod" if inventory_environment == "prod"
      else "test" if inventory_environment == "test" }}

businesscard_image_name: businesscard
businesscard_image_tag: >-
    {{ "prod" if inventory_environment == "prod" else "develop" }}
    
_dinfo_build_keybase_dir: "/keybase/team/epfl_si.build_common"
dinfo_build_cadi_libs_ssh_secret_key_path: "{{ _dinfo_build_keybase_dir }}/id_rsa_c4science_idevfsd-checkouter"
dinfo_build_cadi_libs_ssh_known_hosts_cmd: "ssh-keyscan c4science.ch"

# List of SF mail adresses, separed by quotes
_mail_SF: 'isabelle.chatton@epfl.ch,marc.fromentin@epfl.ch,barbara.scheuner@epfl.ch,businesscard-ops@groupes.epfl.ch'
mail_SF: >-
  {{ _mail_SF if inventory_environment == "prod"
     else "jerome.cosandey@epfl.ch" if inventory_environment == "test" }}
