# Secrets source
_keybase_secrets: 
  prod: "{{ lookup('file', '/keybase/team/epfl_bsnscrd/secrets-prod.yml') | from_yaml }}"
  test: "{{ lookup('file', '/keybase/team/epfl_bsnscrd/secrets-test.yml') | from_yaml }}"

keybase_secrets: "{{ _keybase_secrets.get(inventory_environment, None) }}"

keybase_businesscard_service_mail_account: >-
  {{ lookup('file', '/keybase/team/epfl_bsnscrd/service.yml') | from_yaml }}

# Hosts and routing
businesscard_hostname: >-
  {{ "businesscard.epfl.ch" if inventory_environment == "prod"
    else "businesscard-test.epfl.ch" }}

businesscard_vhost_dir: app

# Tequila
tequila_hostname: tequila.epfl.ch
tequila_environment: prod

# App
quay_registry: quay-its.epfl.ch/svc0077
app_image_name: businesscard
app_image_tag: prod

_pull_robot_secrets: "{{ keybase_secrets.quay.pull_robot }}"
_pull_robot_credential: "{{ _pull_robot_secrets.name }}:{{ _pull_robot_secrets.token }}"

pull_secret_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _pull_robot_credential | b64encode }}"

# Email adresses
mail_SF: "{{ keybase_secrets.mails.sf }}"
mail_repro: "{{ keybase_secrets.mails.repro }}"
